[Match Service] Change database and refactor code
CS3219-AY2223S1/cs3219-project-ay2223s1-g52 pull request #53
Opened 2022-09-13 06:49 UTC by lyeyixian

- change from sqlite3 to mongodb
- refactor code to follow MVC pattern

2022-09-13 14:15 UTC, Marcon2509 reviewed
Can change the 200 in  res status to the constants

2022-09-13 15:59 UTC, Ziyang-98 commented on matching-service/README-matching-service.md
> +- MONGO_URI=mongodb+srv://user3219:user3219@cluster0.fesq8vy.mongodb.net/MatchingService?retryWrites=true&w=majority
hmm not wise to put the mongo_uri here since it contains secret (the password). I think in prod shud remember to remove

2022-09-13 16:18 UTC, Ziyang-98 requested changes
Other than the secret in the md file, everything else looks good!

2022-09-14 06:33 UTC, Ziyang-98 approved these changes
lgtm!

2022-09-14 06:33 UTC, merged